//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.19 at 11:40:36 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.petclinic.com/xml/pets", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.petclinic.xml.pets;
